
import openpyxl
import json

TRANSLATIONS = {
    "STT": "No.",
    "NỘI DUNG": "CONTENT",
    "THÔNG TIN CHI TIẾT": "DETAILS",
    "THACO": "THACO",
    "THACO AUTO": "THACO AUTO",
    "THACO INDUSTRIES": "THACO INDUSTRIES",
    "ĐẠI QUANG MINH": "DAI QUANG MINH",
    "THISO": "THISO",
    "THILOGI": "THILOGI",
    "Ghi chú": "Note",
    "Yêu cầu ghi chi tiết về đăc thù của TĐTV": "Request detailed notes on specific characteristics of member companies",
    "DỮ LIỆU ĐẦU VÀO": "INPUT DATA",
    "Thông tin nhân sự": "Personnel Information",
    "Họ tên": "Full Name",
    "Mã nhân viên": "Employee ID",
    "Ngày sinh": "Date of Birth",
    "Giới tính": "Gender",
    "Ngày vào làm": "Join Date",
    "Phòng ban": "Department",
    "Chức danh": "Title",
    "Loại HĐLĐ": "Labor Contract Type",
    "Mức lương ký hợp đồng lao động lao động hoặc hợp đồng thử việc": "Signed Salary (Labor/Probation Contract)",
    "Lương cơ bản": "Basic Salary",
    "Định mức Thưởng HQCV": "KPI Bonus Norm",
    "Thưởng hiệu quả công việc": "Performance Bonus (KPI)",
    "Lương thu nhập": "Income Salary",
    "Phụ cấp": "Allowance",
    "Lương tháng": "Monthly Salary",
    "Lương ngày": "Daily Salary",
    "Lương giờ": "Hourly Salary",
    "Công chuẩn": "Standard Days",
    "Công thực tế": "Actual Days",
    "Số ngày trong tháng - Số ngày chủ nhật": "Days in month - Sundays",
    "Tăng ca": "Overtime",
    "Tăng ca trả tiền": "Paid Overtime",
    "Nghỉ phép năm": "Annual Leave",
    "Nghỉ ốm": "Sick Leave",
    "Nghỉ chế độ": "Policy Leave",
    "Việc riêng": "Personal Leave",
    "Không lương": "Unpaid Leave",
    "Công tác": "Business Trip",
    "Biệt phái": "Secondment",
    "Lễ Tết": "Holidays",
    "Bảo hiểm xã hội": "Social Insurance",
    "BHXH": "Social Insurance",
    "BHYT": "Health Insurance",
    "BHTN": "Unemployment Insurance",
    "Phí công đoàn": "Union Fee",
    "Thuế TNCN": "PIT",
    "Thực nhận": "Net Pay",
    "Tổng thu nhập": "Total Income",
    "Tạm ứng": "Advance",
    "Khấu trừ": "Deduction",
    "Phụ cấp cơm": "Meal Allowance",
    "Phụ cấp xăng xe": "Petrol Allowance",
    "Phụ cấp điện thoại": "Phone Allowance",
    "Phụ cấp trách nhiệm": "Responsibility Allowance",
    "Phụ cấp độc hại": "Hazard Allowance",
    "Phụ cấp thâm niên": "Seniority Allowance",
    "Phụ cấp khác": "Other Allowances",
    "Ký nhận": "Signature",
    "Ngày": "Date",
    "Tháng": "Month",
    "Năm": "Year",
    "Phê duyệt": "Approved",
    "Người lập": "Prepared by",
    "Kế toán trưởng": "Chief Accountant",
    "Giám đốc": "Director",
    "Tổng Giám đốc": "General Director",
    "Ban Thư ký": "Secretariat",
    "Ban Nhân sự": "HR Department",
    "Phòng HCNS": "HR & Admin Dept",
    "Phần mềm chấm công": "Timekeeping Software",
    "Máy chấm công": "Timekeeper Machine",
    "Vân tay": "Fingerprint",
    "Nhận diện khuôn mặt": "Face Recognition",
    "Thẻ từ": "Magnetic Card",
    "Dữ liệu công": "Attendance Data",
    "Bảng công": "Timesheet",
    "Chốt công": "Close Timesheet",
    "Khóa bảng công": "Lock Timesheet",
    "Lương = Lương Cơ bản + Định mức Thưởng HQCV": "Salary = Basic Salary + KPI Bonus Norm",
    "26 công/tháng": "26 days/month",
    "01 Chu kỳ chốt công trong tháng: Từ ngày 26 tháng trước đến hết ngày 25 tháng hiện tại.": "01 Timesheet Cycle: From 26th of prev month to 25th of current month.",
    "Ca hành chính: 8 tiếng/ngày": "Admin Shift: 8 hours/day",
    "Ca 8h - 17h": "Shift 8h - 17h",
    "Ca gãy": "Split Shift",
    "Ca đêm": "Night Shift",
    "Làm thêm giờ": "Overtime Work",
    "Nghỉ bù": "Compensatory Leave",
    "Nghỉ phép": "Annual Leave",
    "Phép tồn": "Remaining Leave",
    "Quyết toán thuế": "Tax Finalization",
    "Người phụ thuộc": "Dependents",
    "Mã số thuế": "Tax Code",
    "Tài khoản ngân hàng": "Bank Account",
    "Ngân hàng": "Bank",
    "Chi nhánh": "Branch",
    "Ghi chú": "Notes",
    "Quy tắc": "Rules",
    "Chi tiết": "Details",
    "Công thức": "Formula",
    "Thành phần nhân sự": "Personnel Composition",
    "A - Lãnh đạo": "A - Leader",
    "B - Tiềm năng": "B - Potential",
    "C - TBP/CV/NV…": "C - Head/Specialist/Staff...",
    "D - Thừa hành/Công nhân": "D - Execution/Worker", 
    "Đối tượng tính lương": "Salary Calculation Object",
    "Lấy từ chế độ tính lương nhân viên": "Taken from employee salary mode",
    "Lương ngày\nNhân viên làm việc theo ca, được đồng ý từ BLĐ, Các thành phần được BLĐ phê duyệt": "Daily Salary\nShift workers, approved by BOD, other approved categories",
    "Tăng ca trả tiền": "Paid Overtime",
    "Theo chế độ chấm công": "According to timekeeping mode",
    "Chưa có phần mềm chấm công": "No timekeeping software yet",
    "Đã có phần mềm chấm công": "Timekeeping software available",
    "Yêu cầu PM tính lương": "Payroll Software Requirements",
    "Phân tích theo TPNS": "Analysis by HR Component",
    "Yêu cầu PM tính công": "Timekeeping Software Requirements",
    "PHẦN MỀM TÍNH LƯƠNG": "PAYROLL SOFTWARE",
    "Mã số BHXH": "Social Insurance No.",
    "Email": "Email",
    "Địa chỉ": "Address",
    "Số điện thoại": "Phone Number",
    "CMND/CCCD": "ID Card/Citizen ID",
    "Nơi cấp": "Place of Issue",
    "Ngày cấp": "Date of Issue",
    "Trình độ học vấn": "Education Level",
    "Chuyên ngành": "Major",
    "Hộ khẩu thường trú": "Permanent Address",
    "Chỗ ở hiện tại": "Current Address",
    "Tình trạng hôn nhân": "Marital Status",
    "Quốc tịch": "Nationality",
    "Dân tộc": "Ethnicity",
    "Tôn giáo": "Religion",
    "Số tài khoản": "Account Number",
    "Tên ngân hàng": "Bank Name",
    "Chi nhánh ngân hàng": "Bank Branch",
    "Người liên hệ khẩn cấp": "Emergency Contact",
    "Mối quan hệ": "Relationship",
    "Số điện thoại liên hệ": "Contact Phone",
    "Thông tin người phụ thuộc": "Dependent Information",
    "Giảm trừ gia cảnh": "Family Deduction",
    "Bắt đầu": "Start",
    "Kết thúc": "End",
    "Hiệu lực": "Effective",
    "Trạng thái": "Status",
    "Đang làm việc": "Working",
    "Đã nghỉ việc": "Resigned",
    "Nghỉ thai sản": "Maternity Leave",
    "Nghỉ ốm đau": "Sick Leave",
    "Nghỉ không lương": "Unpaid Leave",
    "Thử việc": "Probation",
    "Chính thức": "Official",
    "Thực tập sinh": "Intern",
    "Hợp đồng lao động": "Labor Contract",
    "Hợp đồng thử việc": "Probation Contract",
    "Hợp đồng khoán": "Service Contract",
    "Hợp đồng thời vụ": "Seasonal Contract",
    "Quyết định thôi việc": "Resignation Decision",
    "Quyết định bổ nhiệm": "Appointment Decision",
    "Quyết định điều chuyển": "Transfer Decision",
    "Quyết định tăng lương": "Salary Increase Decision",
    "Tiền mặt": "Cash",
    "Chuyển khoản": "Bank Transfer",
    "Kỳ 1": "Period 1",
    "Kỳ 2": "Period 2",
    "Lần 1": "1st Time",
    "Lần 2": "2nd Time",
    "Tổng cộng": "Total",
    "Diễn giải": "Description",
    "Số tiền": "Amount",
    "Đơn vị": "Unit",
    "Số lượng": "Quantity",
    "Đơn giá": "Unit Price",
    "Thành tiền": "Total Amount",
    "Ghi chú khác": "Other Notes",
    # Add more specific sentences from the file analysis
    "Khóa bảng công": "Lock Timesheet",
    "Đối với Khối sản xuất: Khóa bảng công hàng ngày": "For Production Division: Lock timesheet daily",
    "Ban Nhân sự khóa bảng công khi các bộ phận đã gửi đủ bảng công và đối chiếu dữ liệu công": "HR locks timesheet when depts have submitted full timesheets and reconciled data",
    "Lương ngày: Bằng 150% LCB nhưng không thấp hơn LTN theo số công làm việc thực tế.": "Daily Salary: Equal to 150% Basic Salary but not lower than Income Salary based on actual work days.",
    "Lương ngày: 26 ngày/tháng": "Daily Salary: 26 days/month",
    "Hưởng nguyên lương theo mức Lương cơ bản": "Full salary based on Basic Salary",
    "Hưởng nguyên lương theo mức Lương thu nhập": "Full salary based on Income Salary",
    "Không hưởng lương": "No salary",
    "Không trả lương (Ghi nhận nghỉ bù/Không ghi nhận tăng ca)": "No Pay (Record as Comp Leave/No Overtime)",
    "Bằng: 100% Lương cơ bản": "Equal to: 100% Basic Salary",
    "Bằng: 100% Lương cơ bản * số ngày nghỉ ngừng việc": "Equal to: 100% Basic Salary * num stoppage days",
    "Đối với nhân viên thu ngân: 7,5 giờ / ngày (chưa bao gồm nghỉ giữa ca)": "For cashiers: 7.5 hours/day (excl. break)",
    "Ca gãy: linh động theo tình hình thực tế": "Split shift: Flexible based on actual situation",
    "Thiết lập mã ca chấm công đồng bộ trong hệ thống;": "Setup synchronized shift codes in system;",
    "Cảnh báo khi phát hiện lỗi từ chấm công: thiếu công (đi trễ, về sớm, không chấm công 1 chiều), gán ca bị sai,…": "Alert on attendance errors: missing data (late/early, missing in/out), wrong shift assigned,...",
    "Chế độ phúc lợi chịu thuế TNCN": "Welfare subject to PIT",
    "Các khoản thu nhập khác": "Other Incomes",
    "Các khoản trừ": "Deductions",
    "Các khoản thu hộ": "Collections on behalf",
    "Thực nhận": "Net Salary",
    "01 công đi làm ngày Chủ nhật": "01 workday on Sunday",
    "01 công đi làm ngày Lễ/ Tết": "01 workday on Holiday/Tet",
    "01 công nghỉ bù ngày thứ 7": "01 comp day for Saturday",
    "Công làm việc ngày thứ Bảy được nghỉ": "Work on Saturday off-day",
    "Làm việc vào Chủ Nhật (đầy đủ / nửa ngày)": "Work on Sunday (Full/Half day)",
    "Công việc": "Job",
    "Mô tả công việc": "Job Description",
    "Địa điểm làm việc": "Work Location",
    "Khu vực": "Region",
    "Miền Bắc": "North",
    "Miền Trung": "Central",
    "Miền Nam": "South",
    "Tây Nguyên": "Central Highlands",
    "Nước ngoài": "Overseas",
    "Trong nước": "Domestic",
    "Điện thoại": "Phone",
    "Đồng phục": "Uniform",
    "Cơm trưa": "Lunch",
    "Cơm ca": "Shift Meal",
    "Nhà ở": "Housing",
    "Đi lại": "Transportation",
    "Khác": "Other",
    "Tổng": "Total",
    "Đạt": "Pass",
    "Không đạt": "Fail",
    "Xếp loại": "Ranking",
    "Xuất sắc": "Excellent",
    "Tốt": "Good",
    "Khá": "Fair",
    "Trung bình": "Average",
    "Yếu": "Weak",
    "Kém": "Poor",
    "Tăng ca ngày nghỉ": "Overtime on Day Off",
    "Tăng ca ngày lễ": "Overtime on Holiday",
    "Tăng ca ngày thường": "Overtime on Normal Day",
    "Tăng ca đêm": "Night Overtime",
    "Giờ làm việc": "Working Hours",
    "Giờ vào": "Time In",
    "Giờ ra": "Time Out",
    "Số giờ": "Hours",
    "Số phút": "Minutes",
    "Số công": "Days",
    "Số ngày": "Days counts",
    "Chi tiết lương": "Salary Details",
    "Lịch sử lướng": "Salary History",
    "Điều chỉnh": "Adjustment",
    "Truy thu": "Arrears collection",
    "Truy lĩnh": "Back pay"
}

try:
    file_path = '/Users/adity/Documents/GitHub/gitlocal/Thaco payroll template.xlsx'
    output_path = '/Users/adity/Documents/GitHub/gitlocal/Thaco_payroll_template_English.xlsx'
    
    wb = openpyxl.load_workbook(file_path)
    
    count = 0
    for sheet in wb.worksheets:
        for row in sheet.iter_rows():
            for cell in row:
                if isinstance(cell.value, str):
                    val = cell.value.strip()
                    # Exact match
                    if val in TRANSLATIONS:
                        cell.value = TRANSLATIONS[val]
                        count += 1
                    else:
                        # Try case-insensitive? Or partial?
                        # Let's simple check if the key is in the value (for mixed sentences)
                        # This is risky but useful for simple replacements
                        # For now, strict match or keyphrase replacement
                        for key, trans in TRANSLATIONS.items():
                            if key in val and len(key) > 4: # Only replace significant chunks
                                cell.value = cell.value.replace(key, trans)
                                count += 1
                                break # One replacement per cell to avoid chaos? or multiple? Multple is okay.
    
    wb.save(output_path)
    print(f"Translation completed. Saved to {output_path}. Modified {count} cells.")

except Exception as e:
    print(f"Error: {e}")
