# -*- coding: utf-8 -*-
"""Every component code becomes something a person can read.

WHY. The code stamped on a salary column is the name it carries everywhere — the
formula grid, the payslip line, the contract component, the mapping canvas. Until
now it was generated by ``re.sub(r'[^A-Za-z0-9]', '', label)``, an ASCII-only filter
that DELETED accented Vietnamese letters instead of folding them. "Chi trả phép năm
chưa sử dụng" became ``CHITRPHPNMCHASDNG``: seventeen characters, and the wrong ones.
Nobody can look at a wall of those and tell one insurance line from another, which is
the confusion this programme exists to remove. A field default cannot fix it — every
structure already in the database was named before the new generator existed, and
those are exactly the structures people work in today.

WHAT IS NOT TOUCHED.
  * **Any code that already conforms** — uppercase alphanumeric and at most twelve
    characters. It is left EXACTLY as it is. Churn on a code that was never broken is
    churn on live formulas and contract history for no gain, and it is also what
    makes a second run of this migration a no-op. ``BASIC`` in particular is read by
    name in ``hr_payslip_formula._get_formula_input_values`` and must not move.
  * **Payslip history** — ``hr.payslip.line.code`` and the ``formula_input_values`` /
    ``formula_computed_values`` JSON on payslips already computed. Those record what
    was calculated under the OLD code and would become a lie if rewritten.
  * **Version snapshots** — ``hr.formula.rule.version.snapshot_json``, for the same
    reason.
  * **Any code shared between structures whose contract component cannot follow.**
    ``hr.contract.advantage.template`` is matched by STRING and is global, so a code
    used by two structures may only move if BOTH move to the same new name. Where
    they disagree — or where one of them was skipped because its code already
    conformed — nothing moves at all, and the skip is logged by name.

The rename itself is ``hr.formula.rule._rename_code``, the same code path the studio's
rename button uses, so there is one implementation and it cannot drift.
"""
import logging
from collections import defaultdict

from odoo import SUPERUSER_ID, api
from odoo.tools.sql import table_exists

from odoo.addons.pb_hr_payroll_formula.models import component_code

_logger = logging.getLogger(__name__)

#: How many configurations get their full old→new list printed. Beyond that only
#: counts, so a 250-column demo structure cannot drown the upgrade log.
_VERBOSE_CONFIGS = 6


def _conforms(code):
    return (component_code.is_valid_code(code)
            and len(code) <= component_code.MAX_LEN)


def _propose(config):
    """Return ``{rule_id: new_code}`` for one configuration.

    Codes that already conform are reserved FIRST, so a generated code can never
    land on one of them. Order is (sequence, id) so the result is reproducible.
    """
    rules = config.rule_ids.sorted(key=lambda r: (r.sequence, r.id))
    letters = {r.column_letter for r in rules if r.column_letter}
    taken = {(r.code or '').strip() for r in rules if _conforms((r.code or '').strip())}

    proposals = {}
    for rule in rules:
        current = (rule.code or '').strip()
        if _conforms(current):
            continue
        new = component_code.build_component_code(
            rule.name or current, existing_codes=taken, reserved=letters)
        taken.add(new)
        proposals[rule.id] = new
    return proposals


def _reconcile_shared_codes(env, rules_by_id, proposals):
    """Withdraw any rename that would strand a contract component.

    A contract component template lives at the database level, not inside a
    structure, and ``payroll_import_batch._get_or_create_advantage_template``
    finds it by matching the code as a STRING. Rename one structure's column
    without the template and a SECOND template is minted on the next import,
    leaving every existing ``hr.contract.advantage`` line on the old one — the
    amounts then read 0 with nothing on screen to say why. So: all of the rules
    sharing such a code move together to the same name, or none of them move.
    """
    if 'hr.contract.advantage.template' not in env:
        return 0
    templates = env['hr.contract.advantage.template'].sudo().search([])
    template_codes = {(t.code or '').strip() for t in templates if t.code}
    if not template_codes:
        return 0

    by_old = defaultdict(list)
    for rule in rules_by_id.values():
        code = (rule.code or '').strip()
        if code in template_codes:
            by_old[code].append(rule)

    withdrawn = 0
    for old, rules in by_old.items():
        targets = {proposals.get(r.id) for r in rules}
        if len(targets) == 1 and None not in targets:
            continue
        if targets == {None}:
            continue                      # nothing was going to move anyway
        for rule in rules:
            if proposals.pop(rule.id, None) is not None:
                withdrawn += 1
        _logger.info(
            "MAPFIX A: leaving '%s' alone — it is a contract component shared by %s "
            "and they do not agree on a single new name (%s).",
            old, ', '.join(sorted({r.config_id.display_name for r in rules})),
            ', '.join(sorted(str(t) for t in targets)))
    return withdrawn


def migrate(cr, version):
    if not table_exists(cr, 'hr_formula_rule'):
        return
    env = api.Environment(cr, SUPERUSER_ID, {})
    Config = env['hr.formula.config'].with_context(active_test=False)
    configs = Config.search([], order='id')
    if not configs:
        _logger.info("MAPFIX A: no salary structures in this database — nothing to rename.")
        return

    proposals, rules_by_id, per_config = {}, {}, []
    for config in configs:
        config_proposals = _propose(config)
        proposals.update(config_proposals)
        for rule in config.rule_ids:
            rules_by_id[rule.id] = rule
        per_config.append((config, config_proposals))

    withdrawn = _reconcile_shared_codes(env, rules_by_id, proposals)

    total_rules = len(rules_by_id)
    renamed = skipped = refused = templates_moved = 0
    verbose_left = _VERBOSE_CONFIGS

    for config, config_proposals in per_config:
        # Siblings = the same old code in another structure, moving together.
        applied, failures = 0, []
        lines = []
        for rule in config.rule_ids.sorted(key=lambda r: (r.sequence, r.id)):
            new = proposals.get(rule.id)
            if not new:
                continue
            old = (rule.code or '').strip()
            siblings = [rid for rid, other in rules_by_id.items()
                        if rid != rule.id and (other.code or '').strip() == old
                        and proposals.get(rid) == new]
            outcome = rule._rename_code(new, siblings_renamed=siblings)
            if outcome.get('ok'):
                applied += 1
                if outcome.get('renamed_template'):
                    templates_moved += 1
                lines.append('%s → %s (%s)' % (old, new, rule.name or ''))
            else:
                failures.append('%s: %s' % (old, outcome.get('msg')))

        renamed += applied
        refused += len(failures)
        config_total = len(config.rule_ids)
        skipped += config_total - applied - len(failures)

        state = 'archived ' if not config.active else ''
        _logger.info("MAPFIX A: %s%s (id %s) — %s columns, %s renamed, %s left as they were%s.",
                     state, config.display_name, config.id, config_total, applied,
                     config_total - applied - len(failures),
                     ', %s refused' % len(failures) if failures else '')
        for failure in failures:
            _logger.warning("MAPFIX A: refused in %s — %s", config.display_name, failure)
        if lines and verbose_left > 0:
            verbose_left -= 1
            for line in lines:
                _logger.info("MAPFIX A:    %s", line)

    _logger.info(
        "MAPFIX A complete: %s columns across %s structures — %s renamed, %s already "
        "readable, %s refused, %s withdrawn to protect a shared contract component, "
        "%s contract components renamed alongside.",
        total_rules, len(configs), renamed, skipped, refused, withdrawn, templates_moved)

    # Orphan check, in the same transaction that did the work: a contract component
    # that still has lines but no column answering to its name is the exact failure
    # this migration is built to avoid, so it is looked for rather than assumed away.
    if 'hr.contract.advantage.template' in env:
        live_codes = {(r.code or '').strip() for r in env['hr.formula.rule'].search([])}
        orphans = []
        for template in env['hr.contract.advantage.template'].sudo().search([]):
            code = (template.code or '').strip()
            if code in live_codes:
                continue
            lines = env['hr.contract.advantage'].sudo().search_count(
                [('advantage_template_id', '=', template.id)])
            if lines:
                orphans.append('%s (%s lines)' % (code, lines))
        if orphans:
            _logger.error(
                "MAPFIX A: contract components with recorded lines and no matching column: "
                "%s. Investigate before running payroll.", ', '.join(sorted(orphans)))
        else:
            _logger.info("MAPFIX A: orphan check clean — every contract component carrying "
                         "lines still has a column of the same name.")
