# -*- coding: utf-8 -*-

from odoo import api, fields, models, _
from odoo.exceptions import UserError

from . import pay_period


class HrPayslipRun(models.Model):
    _inherit = ['hr.payslip.run']

    # ------------------------------------------------------------------
    # RUNSRC B2 — the run knows how long a full month is
    # ------------------------------------------------------------------
    # Standard working days used to have to arrive in the spreadsheet every
    # single month, because nothing on the run could answer it. Now the run
    # answers it, defaulting to the plain Mon-Fri count of its own period, and
    # a month with public holidays is adjusted here instead of in the file.
    #
    # STORED AND DEFAULTED, NEVER COMPUTED. A stored compute would silently
    # overwrite that holiday adjustment the next time anything touched the
    # dates — which is precisely the thing this field exists to prevent.
    pb_std_work_days = fields.Float(
        string="Standard working days",
        digits=(16, 2),
        help="How many working days a full month is paid against. Starts as "
             "the Monday-to-Friday count of this period; lower it for a month "
             "with public holidays. Press Recompute Formulas afterwards so the "
             "payslips pick it up.",
    )

    #: What a reader needs the moment the box says 0.00 — which every run made
    #: before this feature existed does, because nothing was back-filled. A
    #: zero there does NOT mean this run is paid against no working days; it
    #: means nobody has said, and the Mon-Fri count of the period answers. The
    #: box alone cannot say that, so this line does. Never stored: it is a
    #: sentence about the value, not a second copy of it.
    pb_std_work_days_note = fields.Char(
        string="What this run is using", readonly=True,
        compute='_compute_pb_std_work_days_note')

    @api.depends('pb_std_work_days', 'date_start', 'date_end')
    def _compute_pb_std_work_days_note(self):
        for run in self:
            if run.pb_std_work_days and run.pb_std_work_days > 0:
                run.pb_std_work_days_note = ''
                continue
            default = pay_period.default_standard_work_days(
                run.date_start, run.date_end)
            run.pb_std_work_days_note = _(
                "Not set, so this run is paid against %s working days — the "
                "Monday-to-Friday days in its own period."
            ) % (('%g' % default) if default else '—')

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('pb_std_work_days'):
                default = pay_period.default_standard_work_days(
                    vals.get('date_start'), vals.get('date_end'))
                if default:
                    vals['pb_std_work_days'] = default
        return super().create(vals_list)

    @api.onchange('date_start', 'date_end')
    def _onchange_pb_std_work_days(self):
        """Fill it from the dates, but only while nobody has said otherwise."""
        for run in self:
            if run.pb_std_work_days and run.pb_std_work_days > 0:
                continue
            default = pay_period.default_standard_work_days(
                run.date_start, run.date_end)
            if default:
                run.pb_std_work_days = default

    def _pb_standard_work_days(self):
        """What this run says its standard working days are, or ``None``.

        Zero and negative are "nobody said", everywhere — a daily rate divided
        by zero standard days is not a number anybody should be paid.
        """
        self.ensure_one()
        value = self.pb_std_work_days or 0.0
        return value if value > 0 else None

    def action_recompute_formula_lines_batch(self):
        """Recompute every payslip in the run that a scheme governs.

        The filter used to be `calculation_method == 'formula'`, which excluded
        exactly the payslips that need this button. A run generated by the Run
        Payroll wizard on a scheme-driven tenant is full of payslips still
        marked 'standard' with no structure and no lines — the ones showing
        0.00 — and pressing Recompute on them answered "No formula-based
        payslips found to recompute". The remedy on screen refused the illness
        it was there to treat.

        A payslip counts if it is already on a scheme, or if it has no salary
        structure and one resolves for it — the same rule the compute path uses,
        so the button and the run agree about what a payslip is. A payslip that
        DOES have a structure is left alone: it has a real standard computation
        and recomputing it from a scheme would replace correct lines.
        """
        total = 0
        for run in self:
            run.slip_ids._adopt_scheme_when_structureless()
            slips = run.slip_ids.filtered(
                lambda s: s.calculation_method == 'formula' and s.formula_config_id
            )
            if slips:
                slips.action_recompute_formula_lines()
                total += len(slips)
        if not total:
            raise UserError(_(
                "Nothing in this pay run is computed from a payroll scheme, so "
                "there is nothing to recompute. Payslips built from a salary "
                "structure are recomputed from the payslip itself."))
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Recomputed'),
                'message': _("Recomputed %s payslip(s).") % total,
                'type': 'success',
            }
        }

    # ------------------------------------------------------------------
    # COLROLES P4 — role-driven leading columns in the payroll workbook
    # ------------------------------------------------------------------
    def _export_base_columns(self, config):
        """Let a structure's own Identity / Employee Profile columns open the sheet.

        The export has always started with a fixed five (MSNV, Full name, Unit,
        contract type, overtime subject) chosen for one Vietnamese workbook. Once a
        structure has roles, it already knows which of ITS columns identify a person
        — so when the structure opts in, those lead instead, in their own order.

        Strictly opt-in: `export_identity_columns` is False by default and, while it
        is, this returns `super()` untouched and the workbook is byte-for-byte what
        it was. Contract, bank and reference columns are deliberately NOT promoted —
        they are people data, not the "who is this row" heading a payroll reviewer
        reads across.

        Lives here rather than in `om_hr_payroll` because the field and the roles
        belong to the formula engine (ledger CR1: never widen om's upgrade surface).
        """
        base = super()._export_base_columns(config)
        if not config or not getattr(config, 'export_identity_columns', False):
            return base

        rules = config.rule_ids.filtered(
            lambda r: (r.column_role or 'payroll') in ('identity', 'profile')
        ).sorted(key=lambda r: (r.sequence, r.id))
        if not rules:
            # Opted in but nothing is marked — falling back to the fixed set beats
            # handing back a workbook with no employee columns at all.
            return base

        columns = []
        for rule in rules:
            code = (rule.code or '').strip().upper()
            name = (rule.name or '').strip().upper()
            keys = []
            if code:
                keys.append(('code', code))
            if name and name != code:
                keys.append(('name', name))
            if not keys:
                continue
            lookup = [k for k in (rule.code, rule.name, rule.column_letter) if k]
            columns.append({
                'header': rule.name or rule.code,
                'keys': keys,
                'lookup': lookup,
                'use_string_payload': True,
            })
        return columns or base
