# -*- coding: utf-8 -*-

from odoo import models, _
from odoo.exceptions import UserError


class HrPayslipRun(models.Model):
    _inherit = ['hr.payslip.run']

    def action_recompute_formula_lines_batch(self):
        """Recompute every payslip in the run that a scheme governs.

        The filter used to be `calculation_method == 'formula'`, which excluded
        exactly the payslips that need this button. A run generated by the Run
        Payroll wizard on a scheme-driven tenant is full of payslips still
        marked 'standard' with no structure and no lines — the ones showing
        0.00 — and pressing Recompute on them answered "No formula-based
        payslips found to recompute". The remedy on screen refused the illness
        it was there to treat.

        A payslip counts if it is already on a scheme, or if it has no salary
        structure and one resolves for it — the same rule the compute path uses,
        so the button and the run agree about what a payslip is. A payslip that
        DOES have a structure is left alone: it has a real standard computation
        and recomputing it from a scheme would replace correct lines.
        """
        total = 0
        for run in self:
            run.slip_ids._adopt_scheme_when_structureless()
            slips = run.slip_ids.filtered(
                lambda s: s.calculation_method == 'formula' and s.formula_config_id
            )
            if slips:
                slips.action_recompute_formula_lines()
                total += len(slips)
        if not total:
            raise UserError(_(
                "Nothing in this pay run is computed from a payroll scheme, so "
                "there is nothing to recompute. Payslips built from a salary "
                "structure are recomputed from the payslip itself."))
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Recomputed'),
                'message': _("Recomputed %s payslip(s).") % total,
                'type': 'success',
            }
        }

    # ------------------------------------------------------------------
    # COLROLES P4 — role-driven leading columns in the payroll workbook
    # ------------------------------------------------------------------
    def _export_base_columns(self, config):
        """Let a structure's own Identity / Employee Profile columns open the sheet.

        The export has always started with a fixed five (MSNV, Full name, Unit,
        contract type, overtime subject) chosen for one Vietnamese workbook. Once a
        structure has roles, it already knows which of ITS columns identify a person
        — so when the structure opts in, those lead instead, in their own order.

        Strictly opt-in: `export_identity_columns` is False by default and, while it
        is, this returns `super()` untouched and the workbook is byte-for-byte what
        it was. Contract, bank and reference columns are deliberately NOT promoted —
        they are people data, not the "who is this row" heading a payroll reviewer
        reads across.

        Lives here rather than in `om_hr_payroll` because the field and the roles
        belong to the formula engine (ledger CR1: never widen om's upgrade surface).
        """
        base = super()._export_base_columns(config)
        if not config or not getattr(config, 'export_identity_columns', False):
            return base

        rules = config.rule_ids.filtered(
            lambda r: (r.column_role or 'payroll') in ('identity', 'profile')
        ).sorted(key=lambda r: (r.sequence, r.id))
        if not rules:
            # Opted in but nothing is marked — falling back to the fixed set beats
            # handing back a workbook with no employee columns at all.
            return base

        columns = []
        for rule in rules:
            code = (rule.code or '').strip().upper()
            name = (rule.name or '').strip().upper()
            keys = []
            if code:
                keys.append(('code', code))
            if name and name != code:
                keys.append(('name', name))
            if not keys:
                continue
            lookup = [k for k in (rule.code, rule.name, rule.column_letter) if k]
            columns.append({
                'header': rule.name or rule.code,
                'keys': keys,
                'lookup': lookup,
                'use_string_payload': True,
            })
        return columns or base
