# -*- coding: utf-8 -*-
"""The 38 components of the Vietnam workbook, each written as a sentence.

This is the **vocabulary proof**: the owner approved a starter called
"Vietnam · Complete" that is the Essentials pack plus the 38 pay components a
real Vietnamese payroll workbook carries. Building that starter is content work
(the next phase). Proving that the guided sentence can SAY all 38 — every
exemption, every proration, every employer share — is engineering work, and it
belongs with the compiler that has to express them.

So this file is not shipped as a template. It is the list of sentences, keyed
by the code each component will own, tested against a live Essentials
configuration, and written so the next phase can lift it verbatim.

Code choices, and why they are what they are:

* twelve characters, capital letters and digits, no underscore — the converter
  contract (`component_code.py`);
* no code is a substring of another, INCLUDING the Essentials codes it will sit
  beside. Substrings are harmless to the converter (MAPFIX settled that), but
  the template registry refuses them at authoring time
  (`formula_config_template.py:199-208`), so a starter built from this list has
  to satisfy the stricter rule;
* the per-component helper inputs the compiler provisions (`UNIFORMYTD`,
  `OTWDHRS`, ...) DO contain their parent's code. They are created on the
  configuration, never in a template, so the registry's rule never sees them.
"""

#: Each entry: code, name, workbook row it comes from, and the sentence.
#: `group` inside the recipe decides which total it feeds.
WORKBOOK_COMPONENTS = [
    # ---- what a person is paid -----------------------------------------
    # The workbook's first row is the salary a person is actually PAID, which
    # is the contract salary prorated by the days they worked. Essentials
    # already has `BASIC` — the contract figure itself, an input — so the paid
    # amount is its own component and `BASIC` becomes plumbing beneath it. It
    # cannot be called BASICPAY: no code may contain another (the template
    # registry refuses it), and BASIC is inside BASICPAY.
    {'code': 'SALARYPAID', 'name': 'Basic salary for the days worked',
     'row': 'BASIC_SALARY',
     'recipe': {'group': 'earning', 'audience': 'all',
                'amount': {'kind': 'contract'},
                'proration': 'working_days', 'frequency': 'monthly',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'included'}}},
    {'code': 'UNIFORM', 'name': 'Uniform allowance', 'row': 'UNIFORM',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'annual_cap',
                              'cap': 5000000.0, 'insurance': 'excluded'}}},
    {'code': 'SEVERSTAT', 'name': 'Statutory severance allowance',
     'row': 'SEVERANCE_STAT',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'entitlement',
                              'insurance': 'excluded'}}},
    {'code': 'OTHEREXMP', 'name': 'Other exempt reimbursement',
     'row': 'OTHER_EXEMPT',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'ALENCASH', 'name': 'Unused annual-leave encashment',
     'row': 'AL_ENCASH_EXEMPT',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'TRANSPADD', 'name': 'Additional transportation',
     'row': 'TRANSPORT_ADD',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'TRANSPORT', 'name': 'Transportation allowance', 'row': 'TRANSPORT',
     'recipe': {'group': 'earning', 'audience': 'role',
                'amount': {'kind': 'role', 'grades': [1200000.0, 800000.0, 500000.0]},
                'proration': 'working_days',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'PHONEALLOW', 'name': 'Phone allowance', 'row': 'PHONE_ALLOW',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'fixed', 'value': 500000.0},
                'proration': 'working_days',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'PRIVINSALW', 'name': 'Private insurance allowance for expats',
     'row': 'PRIVATE_INS_ALLOW',
     'recipe': {'group': 'earning', 'audience': 'foreign',
                'amount': {'kind': 'input'},
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'review'}}},
    {'code': 'PREMINSALW', 'name': 'Premium health cover for family members',
     'row': 'PREMIUM_INS_ALLOW',
     'recipe': {'group': 'earning', 'audience': 'enrolled',
                'amount': {'kind': 'linked', 'link': 'PRIVHLTHDEP'},
                'frequency': 'scheme',
                'treatment': {'cash': 'noncash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'LOGISINC', 'name': 'Logistics incentive', 'row': 'LOGISTICS_INC',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'AGROINC', 'name': 'Season agronomy incentive', 'row': 'AGS_INC',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'scheme',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'LAUNCHINC', 'name': 'New product launch incentive',
     'row': 'PRODUCT_LAUNCH_INC',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'VARPAY', 'name': 'Variable bonus', 'row': 'VARIABLE_BONUS',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'percent_contract', 'percent': 10.0},
                'frequency': 'scheme',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'REFERINC', 'name': 'Referral incentive', 'row': 'REFERRAL_INC',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'OTHERTAX', 'name': 'Other taxable allowance', 'row': 'OTHER_TAXABLE',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'ADJADD', 'name': 'Prior-period addition', 'row': 'ADJ_ADD',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'inherit',
                              'source_code': 'BASIC', 'insurance': 'inherit'}}},
    {'code': 'ADJDEDUCT', 'name': 'Prior-period deduction adjustment',
     'row': 'ADJ_DEDUCT',
     'recipe': {'group': 'earning', 'sign': -1,
                'amount': {'kind': 'input'}, 'frequency': 'adhoc',
                'treatment': {'cash': 'cash', 'tax': 'inherit',
                              'source_code': 'BASIC', 'insurance': 'inherit'}}},
    {'code': 'NONCASHBEN', 'name': 'Taxable non-cash benefit',
     'row': 'NONCASH_BENEFIT',
     'recipe': {'group': 'earning', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'cash': 'noncash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},
    {'code': 'OTWD', 'name': 'Weekday overtime pay', 'row': 'OT_WEEKDAY',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'hourly', 'rate_pct': 150.0},
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'OTWE', 'name': 'Weekend overtime pay', 'row': 'OT_WEEKEND',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'hourly', 'rate_pct': 200.0},
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'OTHOL', 'name': 'Public-holiday overtime pay', 'row': 'OT_HOLIDAY',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'hourly', 'rate_pct': 300.0},
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'NIGHTPREM', 'name': 'Night-work premium', 'row': 'NIGHT_SHIFT',
     'recipe': {'group': 'earning',
                'amount': {'kind': 'hourly', 'rate_pct': 30.0},
                'treatment': {'cash': 'cash', 'tax': 'qualified',
                              'insurance': 'excluded'}}},
    {'code': 'MONTH13', 'name': 'Thirteenth-month salary',
     'row': 'THIRTEENTH_MONTH',
     'recipe': {'group': 'earning', 'frequency': 'annual',
                'amount': {'kind': 'annual_ratio', 'payout_month': 1},
                'treatment': {'cash': 'cash', 'tax': 'taxable',
                              'insurance': 'excluded'}}},

    # ---- what comes off ------------------------------------------------
    {'code': 'SIDED', 'name': 'Employee social insurance', 'row': 'EE_SI',
     'recipe': {'group': 'deduction',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'rate_code': 'SIRATE'},
                'treatment': {'tax': 'exempt', 'pit_deductible': 'yes'}}},
    {'code': 'HIDED', 'name': 'Employee health insurance', 'row': 'EE_HI',
     'recipe': {'group': 'deduction',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'rate_code': 'HIRATE'},
                'treatment': {'tax': 'exempt', 'pit_deductible': 'yes'}}},
    {'code': 'UIDED', 'name': 'Employee unemployment insurance', 'row': 'EE_UI',
     'recipe': {'group': 'deduction', 'audience': 'local',
                'amount': {'kind': 'percent_of', 'base': 'UIBASE',
                           'rate_code': 'UIRATE'},
                'treatment': {'tax': 'exempt', 'pit_deductible': 'yes'}}},
    {'code': 'UNIONDUES', 'name': 'Employee union dues', 'row': 'UNION_DUES',
     'recipe': {'group': 'deduction', 'audience': 'union',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'percent': 0.5},
                'treatment': {'tax': 'exempt', 'pit_deductible': 'no'}}},
    {'code': 'PIT', 'name': 'Personal income tax', 'row': 'PIT',
     'recipe': {'group': 'deduction',
                'amount': {'kind': 'bracket', 'table': 'VNTAX',
                           'base': 'TAXABLE'},
                'treatment': {'tax': 'exempt', 'is_income_tax': True}}},
    {'code': 'ADVANCE', 'name': 'Salary advance recovery', 'row': 'ADVANCE',
     'recipe': {'group': 'deduction', 'amount': {'kind': 'input'},
                'frequency': 'adhoc', 'treatment': {'tax': 'exempt'}}},
    {'code': 'PRIORDED', 'name': 'Prior-period deduction', 'row': 'PRIOR_DED',
     'recipe': {'group': 'deduction', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'tax': 'exempt', 'pit_deductible': 'source',
                              'source_code': 'BASIC'}}},
    {'code': 'OTHERDED', 'name': 'Other deduction', 'row': 'OTHER_DED',
     'recipe': {'group': 'deduction', 'amount': {'kind': 'input'},
                'frequency': 'adhoc', 'treatment': {'tax': 'exempt'}}},

    # ---- what the employer pays on top ----------------------------------
    {'code': 'SHUILOCAL', 'name': 'Employer social, health and unemployment cover',
     'row': 'VN_SHUI_LOCAL',
     'recipe': {'group': 'benefit', 'audience': 'local',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'percent': 21.5},
                'treatment': {'tax': 'exempt', 'employer_share_pct': 100.0}}},
    {'code': 'SHUIFOREIGN', 'name': 'Employer cover for foreign employees',
     'row': 'VN_SI_HI_FOREIGN',
     'recipe': {'group': 'benefit', 'audience': 'foreign',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'percent': 20.5},
                'treatment': {'tax': 'exempt', 'employer_share_pct': 100.0}}},
    {'code': 'PRIVHLTHEE', 'name': 'Private health cover — employee',
     'row': 'PRIVATE_HEALTH_EMP',
     'recipe': {'group': 'benefit', 'audience': 'enrolled',
                'amount': {'kind': 'input'}, 'frequency': 'scheme',
                'treatment': {'tax': 'taxable', 'cash': 'noncash',
                              'employer_share_pct': 100.0}}},
    {'code': 'PRIVHLTHDEP', 'name': 'Private health cover — dependants',
     'row': 'PRIVATE_HEALTH_DEP',
     'recipe': {'group': 'benefit', 'audience': 'enrolled',
                'amount': {'kind': 'input'}, 'frequency': 'scheme',
                'treatment': {'tax': 'taxable', 'cash': 'noncash',
                              'employer_share_pct': 100.0}}},
    {'code': 'UNIONER', 'name': 'Employer union contribution',
     'row': 'UNION_MEMBER',
     'recipe': {'group': 'benefit',
                'amount': {'kind': 'percent_of', 'base': 'SIBASE',
                           'percent': 2.0},
                'treatment': {'tax': 'exempt', 'employer_share_pct': 100.0}}},
    {'code': 'OTHERBEN', 'name': 'Other company benefits', 'row': 'OTHER_BENEFITS',
     'recipe': {'group': 'benefit', 'amount': {'kind': 'input'},
                'frequency': 'adhoc',
                'treatment': {'tax': 'taxable', 'cash': 'noncash',
                              'insurance': 'review',
                              'employer_share_pct': 100.0}}},
]

#: Codes only, in order — handy for a test and for the next phase's template.
WORKBOOK_CODES = [c['code'] for c in WORKBOOK_COMPONENTS]
