const BLUEPRINT_STEPS=['Your blueprint','Pay components','Tax & protection','Pay & deliver','Prove it works','Review & create'];
const BP_BANDS=[{lower:0,rate:5},{lower:10000000,rate:10},{lower:30000000,rate:20},{lower:60000000,rate:30},{lower:100000000,rate:35}];
const BP_CONNECTIONS=[
 {title:'Tax tables',screen:'Statutory → Tax Tables',model:'hr.formula.config.vn_tax_table_id → vietnam.tax.table; hr.formula.rate.table',status:'Snapshot proposed',detail:'Choose an approved, effective-dated tax master; pin its bands and relief to this configuration. Formula Studio uses its own rate tables. The current source-code default creates 2024 bands; never assume it is the approved 2026 pack.',gap:'The config already links to a tax master via vn_tax_table_id. A pinned version bridge to Formula Studio bands and approval check are proposed. This preview reads workbook values, not live company records.'},
 {title:'Insurance policies',screen:'Statutory → Insurance Policies',model:'hr.formula.config.vn_insurance_policy_id → vietnam.insurance.policy',status:'Existing model',detail:'Select the policy by company, effective date and employee eligibility. Keep SI/HI/UI ceilings, employee deductions and employer costs separate.',gap:'The config already has vn_insurance_policy_id and a company-default switch. Effective-date resolution and an approved snapshot still need to be wired into the blueprint payload.'},
 {title:'Employee, contract & bank',screen:'Formula Studio → Data mapping',model:'hr.employee · hr.contract · res.partner.bank',status:'Existing screen',detail:'Salary, residency, dependants and eligibility are typed inputs. Bank account lanes are separate from calculation inputs. Preserve account numbers as text.',gap:'Required-input contracts, damaged-account checks and employee-specific effective dates must be enforced by the adapter.'},
 {title:'Payroll calendar & corrections',screen:'Payroll cycles · Retro adjustments',model:'hr.payroll.cycle.component.mapping · payroll retro / proration models',status:'Workflow extension',detail:'Pair mid-cycle advances with end-cycle recovery. Segment joiners, leavers and rate changes. Corrections need an original period and source component.',gap:'Historical tax recomputation, YTD accumulators and segment aggregation are integration recipes, not simulated by a single monthly amount.'},
 {title:'Bank file & release',screen:'Pay & Deliver',model:'pb.bank.file.layout · pb.bank.file.column',status:'Mapping extension',detail:'The bank layout is a delivery contract, not a formula. Reconcile file totals with approved net pay; validate account text, bank identifier type, currency and value date.',gap:'The existing source enum does not cover all workbook fields such as bank code, currency, email and FX. Extend it before using this proposed layout.'},
 {title:'Payslip layout',screen:'Payslip Configuration · Pay & Deliver',model:'hr.payslip.config',status:'Existing model',detail:'Keep bilingual labels, grouping, zero suppression and confidentiality separate from calculation rules. Release after confirmed payment.',gap:'Bind generated component codes to the selected structure and layout. This preview uses synthetic employees only.'},
 {title:'Formula Engine & release',screen:'Formula Studio → Formulas · Test · Review',model:'hr.formula.config · hr.formula.rule · formula review / release models',status:'Adapter required',detail:'Persist each rule as excel_formula with its code, input mapping, dependency order and category. Keep manual edits, version comparisons, sample data and release evidence.',gap:'create_config currently seeds templates; it does not ingest this blueprint. A validated create-from-blueprint adapter is required. Export is a proposal, not a live activation payload.'}
];
function newBlueprint(){return {version:2,name:'Vietnam · Monthly payroll',cycle:'end',step:0,group:'earnings',people:['local'],components:defaults(),rules:{...DEFAULT_RULES},bands:structuredClone(BP_BANDS),overrides:{},delivery:{currency:'VND',fx:26071,cutoff:15,payday:'penultimate',late:'next',bank:'generic',account:'001234567890',bankCode:'970436',bankCodeType:'napas',language:'both',hideZero:true,release:'confirmed',approvals:true},scenarios:['joiner','foreign','short','benefit','annual'],sample:sampleProfile(),reviews:{},tested:false,created:false};}
function checkBands(bands){if(!Array.isArray(bands)||bands.length<1)throw Error('Add at least one tax band.');if(bands[0].lower!==0)throw Error('The first tax band must start at 0.');bands.forEach((b,i)=>{if(!Number.isFinite(b.lower)||b.lower<0||!Number.isFinite(b.rate)||b.rate<0||b.rate>=100)throw Error('Use non-negative thresholds and rates from 0 to less than 100%.');if(i&&b.lower<=bands[i-1].lower)throw Error('Tax thresholds must increase. Duplicate or overlapping starts are not allowed.');});}
function bpTax(x,bands){checkBands(bands);let t=0;bands.forEach((b,i)=>{t+=Math.max(0,Math.min(Math.max(x,0),bands[i+1]?.lower??Infinity)-b.lower)*b.rate/100});return t;}
function bpTaxExcel(x,bands){checkBands(bands);return 'SUM('+bands.map((b,i)=>`MAX(0,${i<bands.length-1?`MIN((${x}),${bands[i+1].lower})`:`(${x})`}-${b.lower})*${b.rate/100}`).join(',')+')';}
// A small, explicit Excel parser. No eval / Function; the same parsed formulas drive the preview.
function parseExcel(formula){
 if(typeof formula!=='string'||!formula.startsWith('='))throw Error('Start your Excel formula with =.');
 const src=formula.slice(1),tokens=[];let at=0;
 while(at<src.length){if(/\s/.test(src[at])){at++;continue}const rest=src.slice(at);let m;if((m=rest.match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/))){tokens.push({type:'n',value:Number(m[0])});at+=m[0].length}else if((m=rest.match(/^"(?:[^"]|"")*"/))){tokens.push({type:'s',value:m[0].slice(1,-1).replaceAll('""','"')});at+=m[0].length}else if((m=rest.match(/^[A-Za-z_][A-Za-z0-9_]*/))){tokens.push({type:'id',value:m[0].toUpperCase()});at+=m[0].length}else if((m=rest.match(/^(?:>=|<=|<>|[+\-*/^%=<>(),])/))){tokens.push({type:m[0]});at+=m[0].length}else throw Error('Unsupported Excel syntax near '+rest.slice(0,18)+'. Use component codes and the supported functions.');}
 let p=0;const peek=()=>tokens[p]?.type,take=t=>{if(peek()!==t)throw Error('Expected '+t+' in formula.');return tokens[p++]};
 function primary(){if(peek()==='n'||peek()==='s')return {value:tokens[p++].value};if(peek()==='id'){const name=tokens[p++].value;if(peek()==='('){p++;const args=[];if(peek()!==')'){args.push(expr());while(peek()===','){p++;args.push(expr())}}take(')');if(!['IF','AND','OR','NOT','SUM','MIN','MAX','ROUND','FLOOR','ABS'].includes(name))throw Error(name+' is not supported in this preview.');return {fn:name,args}}return {ref:name}}if(peek()==='('){p++;const a=expr();take(')');return a}throw Error('Expected an amount, component code or function.');}
 function unary(){if(peek()==='-'||peek()==='+'){const op=tokens[p++].type;return {op:'u'+op,a:unary()}}let a=primary();while(peek()==='%'){p++;a={op:'/',a,b:{value:100}}}return a}
 function power(){let a=unary();if(peek()==='^'){p++;a={op:'^',a,b:power()}}return a}
 function mul(){let a=power();while(['*','/'].includes(peek())){const op=tokens[p++].type;a={op,a,b:power()}}return a}
 function add(){let a=mul();while(['+','-'].includes(peek())){const op=tokens[p++].type;a={op,a,b:mul()}}return a}
 function expr(){let a=add();if(['=','<>','<','>','<=','>='].includes(peek())){const op=tokens[p++].type;a={op,a,b:add()}}return a}
 const ast=expr();if(p!==tokens.length)throw Error('Unexpected content after the formula.');return ast;
}
function excelRefs(e){return e.ref?[e.ref]:e.args?[...new Set(e.args.flatMap(excelRefs))]:e.op?[...new Set([...excelRefs(e.a),...(e.b?excelRefs(e.b):[])])]:[];}
function calcExcel(e,resolve){if('value'in e)return e.value;if(e.ref)return resolve(e.ref);if(e.op){const a=calcExcel(e.a,resolve);if(e.op==='u-')return -a;if(e.op==='u+')return +a;const b=calcExcel(e.b,resolve);switch(e.op){case'+':return a+b;case'-':return a-b;case'*':return a*b;case'/':if(b===0)throw Error('Division by zero: check scheduled days, hours or FX.');return a/b;case'^':return a**b;case'=':return a===b;case'<>':return a!==b;case'<':return a<b;case'>':return a>b;case'<=':return a<=b;case'>=':return a>=b;}}
 if(e.fn==='IF'){if(e.args.length!==3)throw Error('IF needs condition, yes and no values.');return calcExcel(e.args[0],resolve)?calcExcel(e.args[1],resolve):calcExcel(e.args[2],resolve)}
 const a=e.args.map(x=>calcExcel(x,resolve));switch(e.fn){case'SUM':return a.reduce((n,v)=>n+Number(v),0);case'MIN':return Math.min(...a);case'MAX':return Math.max(...a);case'AND':return a.every(Boolean);case'OR':return a.some(Boolean);case'NOT':if(a.length!==1)throw Error('NOT needs one value.');return !a[0];case'ABS':if(a.length!==1)throw Error('ABS needs one value.');return Math.abs(a[0]);case'ROUND':if(a.length!==2||!Number.isInteger(a[1]))throw Error('ROUND needs a value and integer decimal places.');return Math.sign(a[0])*Math.round((Math.abs(a[0])+Number.EPSILON)*10**a[1])/10**a[1];case'FLOOR':if(a.length!==2||a[1]<=0)throw Error('FLOOR needs a positive significance.');return Math.floor(a[0]/a[1])*a[1];}throw Error('Unknown Excel function.');}
function compileBlueprint(b){
 checkBands(b.bands);
 const errors=issues(b).filter(x=>x.severity==='error');if(errors.length)throw Error(errors[0].title+': '+errors[0].detail);
 for(const [key,v] of Object.entries(b.rules)){if(typeof v==='number'&&(!Number.isFinite(v)||v<0))throw Error('Invalid non-negative parameter: '+key);}
 if(b.rules.shortRate>=100||b.rules.nonresidentRate>=100)throw Error('Tax rates must be below 100%.');
 if(!/^\d{4}-\d{2}-\d{2}$/.test(b.rules.effective))throw Error('Choose an effective date.');
 if(!Number.isInteger(b.delivery.cutoff)||b.delivery.cutoff<1||b.delivery.cutoff>28)throw Error('Choose a cutoff day from 1 to 28 for a monthly calendar.');
 for(const c of b.components.filter(c=>c.included)){for(const key of ['amount','rate','cap','employeeShare','erSi','erHi','erUi'])if(!Number.isFinite(c[key])||c[key]<0)throw Error(c.name+': '+key+' must be a non-negative number.');if(c.employeeShare>100)throw Error(c.name+': employee share cannot exceed 100%.');if(!Number.isInteger(c.month)||c.month<1||c.month>12)throw Error(c.name+': choose a payout month from 1 to 12.');}
 const base=compile(b),inputMap=Object.fromEntries(base.inputs.map(x=>[x.code,{...x,description:x.code.toLowerCase().replaceAll('_',' ')}]));const nodes=[];
 const addInput=(code,value,description='',type='number')=>{if(!inputMap[code])inputMap[code]={code,type,default:value,description:description||code.toLowerCase().replaceAll('_',' ')};return code};
 const resident=addInput('IS_RESIDENT',1),local=addInput('IS_LOCAL',1),insured=addInput('IS_INSURED',1),union=addInput('IS_UNION_MEMBER',1),months=addInput('CONTRACT_MONTHS',12),commit=addInput('VALID_TAX_COMMITMENT',0),month=addInput('PAY_MONTH',9),role=addInput('ROLE_CODE',1,'1 = AG, 2 = territory manager, 3 = compliance officer, 0 = other');
 const elig=(kind,code)=>kind==='all'?'1':kind==='local'?local:kind==='foreign'?`(${local}=0)`:kind==='insured'?insured:kind==='union'?union:kind==='role'?`(${role}>0)`:addInput(code+'_ENROLLED',0);
 const totalTax=(g,d,p,dep)=>`IF(${resident}=0,MAX(0,(${g}))*${b.rules.nonresidentRate/100},IF(${months}<3,IF(AND((${g})>=${b.rules.shortThreshold},${commit}=0),MAX(0,(${g}))*${b.rules.shortRate/100},0),${bpTaxExcel(`MAX(0,(${g})-(${d})-(${p})-(${dep}))`,b.bands)}))`;
 const premium=code=>{const c=b.components.find(c=>c.code===code&&c.included);if(!c)return '0';return `IF(${elig(c.eligibility,code)},${c.amount||addInput(code+'_PREMIUM',0)},0)`};
 function convert(e){if(e.ref){const percentage=b.components.find(c=>c.group==='earnings'&&c.mode==='percentage'&&c.included&&e.ref===c.code+'_INPUT');return percentage?`(CONTRACT_SALARY*${percentage.rate/100})`:e.ref;}if('value'in e)return typeof e.value==='string'?JSON.stringify(e.value):String(e.value);const a=e.args.map(convert),v=e.args.map(x=>x.value);
 switch(e.fn){case'ADD':case'SUM':return `SUM(${a.join(',')})`;case'SUB':return '('+a.join('-')+')';case'MUL':return '('+a.join('*')+')';case'DIV':return '('+a.join('/')+')';case'ROUND':return `ROUND(${a[0]},0)`;case'FLOOR':return `FLOOR(${a[0]},1)`;case'ELIGIBLE':return elig(v[0],v[1]);case'DUE':return v[1]==='annual'?`(${month}=${v[2]})`:['scheme','adhoc'].includes(v[1])?addInput(v[0]+'_DUE',1,'Approved and due in this payroll: 1 yes / 0 no'):'1';case'QUALIFIED':return addInput(v[0]+'_QUALIFIED',1,'Evidence confirms exemption: 1 yes / 0 no');case'EMPLOYER_UNION_ELIGIBLE':return addInput('EMPLOYER_UNION_ELIGIBLE',1);case'ROLE_RATE':return `IF(${role}=1,${a[1]},IF(${role}=2,${a[2]},IF(${role}=3,${a[3]},0)))`;case'PLAN_PREMIUM':return premium(v[0]);case'PLAN_ER_PREMIUM':return `(${premium(v[0])}*${1-(b.components.find(c=>c.code===v[0])?.employeeShare||0)/100})`;case'ORIGINAL_TAXABLE':return `(${a[1]}*${addInput((v[0]||'UNRESOLVED')+'_ORIGINAL_TAX_RATIO',1,'Approved original taxable fraction, 0–1; historical re-run not simulated')})`;case'ORIGINAL_INSURANCE':return `(${a[1]}*${addInput((v[0]||'UNRESOLVED')+'_ORIGINAL_INSURANCE_RATIO',0,'Approved original insurance fraction, 0–1')})`;case'TAX':return totalTax(...a);case'GROSS_UP':{
 const [g,born,d,p,dep]=a;let prev='0';const baseline=totalTax(`MAX(0,${g}-${born})`,d,p,dep);
 for(let i=1;i<=32;i++){const code='PIT_ITER_'+i;nodes.push({code,name:'Employer PIT · calculation step '+i,group:'internal',excel_formula:`=MAX(0,${totalTax(`${g}+${prev}`,d,p,dep)}-${baseline})`,source:'Generated non-circular Excel gross-up helper'});prev=code;}
 nodes.push({code:'GROSS_UP_RESIDUAL',name:'Gross-up precision check',group:'checks',excel_formula:`=ABS(${prev}-MAX(0,${totalTax(`${g}+${prev}`,d,p,dep)}-${baseline}))`,source:'Must be below 1 VND'});return `ROUND(${prev},0)`;}
 default:return `${e.fn}(${a.join(',')})`;}}
 for(const n of base.nodes){let excel_formula='='+convert(n.expr);const c=b.components.find(c=>c.code===n.code&&c.included);if(c?.group==='earnings'&&c.mode==='percentage'){let amount=`(CONTRACT_SALARY*${c.rate/100})`;if(c.proration==='working')amount=`(${amount}*PAID_DAYS/STANDARD_DAYS)`;if(c.proration==='calendar')amount=`(${amount}*PAID_CALENDAR_DAYS/CALENDAR_DAYS)`;const due=c.frequency==='annual'?`PAY_MONTH=${c.month}`:['adhoc','scheme'].includes(c.frequency)?addInput(c.code+'_DUE',1):'1';excel_formula=`=${b.rules.rounding==='floor'?'FLOOR':'ROUND'}(IF(AND(${elig(c.eligibility,c.code)},${due}),${amount}*${c.sign},0),${b.rules.rounding==='floor'?1:0})`;}
 nodes.push({code:n.code,name:n.name,group:n.group,excel_formula,source:n.source});}
 if(b.delivery.currency==='USD')nodes.push({code:'PAYMENT_AMOUNT',name:'Bank payment · USD',group:'outputs',excel_formula:`=ROUND(NET_PAY/${addInput('APPROVED_FX_RATE',b.delivery.fx,'Approved VND per USD; payroll calculation remains VND')},2)`,source:'Bank Accounts · approved FX'});
 else nodes.push({code:'PAYMENT_AMOUNT',name:'Bank payment · VND',group:'outputs',excel_formula:'=ROUND(NET_PAY,0)',source:'Bank File Spec'});
 for(const n of nodes){n.generated_formula=n.excel_formula;if(b.overrides[n.code]){n.excel_formula=b.overrides[n.code];n.manual=true}n.ast=parseExcel(n.excel_formula);n.dependencies=excelRefs(n.ast);}
 const codes=new Set([...Object.keys(inputMap),...nodes.map(n=>n.code)]);if(codes.size!==Object.keys(inputMap).length+nodes.length)throw Error('Duplicate component or input code.');for(const n of nodes)for(const ref of n.dependencies)if(!codes.has(ref))throw Error(n.code+' refers to missing '+ref+'. Restore the component or update its formula.');
 return {format:'payobook.blueprint.excel.v2',productionCompatible:false,name:b.name,country_code:'VN',cycle_type:b.cycle,currency:'VND',paymentCurrency:b.delivery.currency,effectiveFrom:b.rules.effective,inputs:Object.values(inputMap),nodes,components:b.components.filter(c=>c.included),bands:b.bands,delivery:b.delivery,connections:BP_CONNECTIONS,removed:b.components.filter(c=>!c.included).map(c=>c.code),note:'Excel rule proposal. Requires validated adapter to existing models; no production records are created.'};
}
function bpInputValues(schema,s){const vals={},mapped={CONTRACT_SALARY:s.salary,PAID_DAYS:s.paidDays,STANDARD_DAYS:s.standardDays,CALENDAR_DAYS:s.calendarDays,PAID_CALENDAR_DAYS:s.paidCalendarDays,HOURS_PER_DAY:s.hoursPerDay,REGISTERED_DEPENDANTS:s.dependants,UNIFORM_YTD_EXEMPT:s.uniformYtd,APPROVED_SEVERANCE_ENTITLEMENT:s.entitlement,ELIGIBLE_ANNUAL_DAYS:s.serviceDays,ANNUAL_SCHEDULED_DAYS:s.annualDays,IS_RESIDENT:+s.resident,IS_LOCAL:+(s.nationality==='local'),IS_INSURED:+s.insured,IS_UNION_MEMBER:+s.union,EMPLOYER_UNION_ELIGIBLE:+s.employerUnion,CONTRACT_MONTHS:s.contractMonths,VALID_TAX_COMMITMENT:+s.commitment,PAY_MONTH:s.month,ROLE_CODE:{AG:1,TM:2,CO:3,OTHER:0}[s.role]??0};for(const i of schema.inputs){let v=i.default;if(i.code in mapped)v=mapped[i.code];else if(i.code.endsWith('_INPUT')){const c=schema.components.find(c=>c.code===i.code.slice(0,-6));v=c?.group==='earnings'&&c.mode==='percentage'?s.salary*c.rate/100:s.values[i.code.slice(0,-6)]||0;}else if(i.code.endsWith('_HOURS'))v=s.values[i.code.slice(0,-6)]||0;else if(i.code.endsWith('_PREMIUM'))v=s.values[i.code.slice(0,-8)]||0;else if(i.code.endsWith('_ENROLLED'))v=+s.benefitEnrolled;else if(i.code.endsWith('_QUALIFIED'))v=+s.qualified;else if(i.code.endsWith('_DUE'))v=+(s.due[i.code.slice(0,-4)]??true);vals[i.code]=v;}return vals;}
function runBlueprint(schema,s){
 if(s.standardDays<=0||s.calendarDays<=0||s.hoursPerDay<=0||s.annualDays<=0)throw Error('Scheduled days and hours must be greater than zero.');if(s.paidDays<0||s.paidDays>s.standardDays)throw Error('Paid days must be between zero and scheduled days.');if(s.salary<0||s.dependants<0||!Number.isInteger(s.dependants))throw Error('Check salary and registered dependant count.');
 const values=bpInputValues(schema,s),by=Object.fromEntries(schema.nodes.map(n=>[n.code,n])),visiting=new Set();
 function resolve(code){if(Object.hasOwn(values,code))return values[code];if(visiting.has(code))throw Error('Circular formula dependency at '+code+'.');if(!by[code])throw Error('Missing input '+code);visiting.add(code);const v=calcExcel(by[code].ast,resolve);if(typeof v!=='number'&&typeof v!=='boolean'||!Number.isFinite(Number(v)))throw Error('Invalid result for '+code);values[code]=v;visiting.delete(code);return v;}
 schema.nodes.forEach(n=>resolve(n.code));if(values.GROSS_UP_RESIDUAL>=1)throw Error('Employer tax calculation did not converge within 1 VND. Review rates or provide a tested gross-up formula.');return values;
}
function bpBankIssues(d){const out=[];if(!/^\d{6,34}$/.test(d.account))out.push('Account must be 6–34 digits in this demo layout; preserve leading zeros and reject scientific notation.');if(d.bankCodeType==='napas'&&!/^\d{6}$/.test(d.bankCode))out.push('NAPAS code must contain six digits.');if(d.bankCodeType==='bic'&&!/^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/.test(d.bankCode))out.push('BIC must have 8 or 11 valid characters.');if(d.currency==='USD'&&(!Number.isFinite(d.fx)||d.fx<=0))out.push('An approved FX rate greater than zero is required.');return out;}
function bpReviews(b){const out=issues(b).map(x=>({...x,title:x.title,detail:x.detail}));if(!b.reviews.tax)out.push({code:'tax',title:'Pin an approved tax-table version',detail:'Workbook pack is a proposal; tax master data has not been read from your company.'});if(!b.reviews.bank)out.push({code:'bank',title:'Confirm bank format with a sample acceptance file',detail:'Bank identifier types and transmitted columns need confirmation. Validation helpers must stay out of the payment file.'});if(!b.reviews.opening)out.push({code:'opening',title:'Reconcile migration and year-to-date balances',detail:'Workbook start-date and opening-balance notes differ. Employee Master, GL Mapping and UAT tabs referenced by the dashboard are absent.'});if(b.people.includes('net'))out.push({code:'net',title:'Net-contract recipe needs an integration test',detail:'Employer-paid benefit PIT is calculated here. A guaranteed net contract needs a separate approved inversion recipe including insurance and rounding.'});if(b.scenarios.includes('retro'))out.push({code:'retro',title:'Connect historical recalculation',detail:'Prior-period rows need original period, tax version, YTD impact and settlement rules. This preview only calculates current-period corrections.'});if(b.scenarios.includes('segments'))out.push({code:'segments',title:'Connect effective-dated pay segments',detail:'Aggregate segment-level salary and calendar inputs from existing proration records. One monthly denominator is insufficient for multiple rate changes.'});bpBankIssues(b.delivery).forEach(x=>out.push({code:'bank',title:'Bank validation',detail:x,severity:'error'}));if(!b.name.trim())out.push({code:'name',title:'Name your configuration',detail:'A configuration name is required.',severity:'error'});if(!b.tested)out.push({code:'test',title:'Run the scenario checks',detail:'Check the generated Excel formulas against sample inputs before handing over.'});return out;}
function bpChecks(b){const results=[],push=(name,fn)=>{try{const detail=fn();results.push({name,pass:true,detail:detail||'Passed'})}catch(e){results.push({name,pass:false,detail:e.message})}};
 push('Every formula parses and all references resolve',()=>{runBlueprint(compileBlueprint(b),sampleProfile());return 'Excel formulas evaluated; no missing references or cycles'});
 push('Tax bands are continuous at every boundary',()=>{checkBands(b.bands);for(const r of b.bands.slice(1)){if(Math.abs(bpTax(r.lower,b.bands)-bpTax(r.lower-1,b.bands))>1)throw Error('Boundary discontinuity')}return b.bands.length+' editable marginal bands checked'});
 for(const [kind,name]of [['standard','Full month'],['joiner','Mid-month joiner'],['foreign','Non-resident foreign employee'],['short','Short contract'],['benefit','Employer-paid benefits']])push(name,()=>{const v=runBlueprint(compileBlueprint(b),sampleProfile(kind));if(Math.abs(v.NET_PAY-(v.CASH_GROSS+v.TAX_GROSS_UP-v.DEDUCTIONS-v.PIT))>.01)throw Error('Net pay does not reconcile');return 'Net pay '+Math.round(v.NET_PAY).toLocaleString('en-US')+' VND · reconciles'});
 push('Zero scheduled days are caught before calculation',()=>{try{runBlueprint(compileBlueprint(b),{...sampleProfile(),standardDays:0})}catch(e){if(e.message.includes('Scheduled'))return 'Invalid input blocked';throw e}throw Error('Invalid denominator accepted')});
 push('Bank fields preserve account text and validate identifiers',()=>{const e=bpBankIssues(b.delivery);if(e.length)throw Error(e.join(' '));return 'Synthetic account and identifier validated; bank acceptance still required'});return results;}
