# -*- coding: utf-8 -*-
from . import (
    hiring_common,
    country_rule,
    requisition,
    requisition_approval,
    jd,
    jd_approval,
    referral,
    posting,
    stage_log,
    interview,
    panel_feedback,
    # A3. The order matters in one place only: `offer` declares the model that
    # `bgv`, `docreq`, `offer_approval` and `offer_closure` extend or point at,
    # and `requisition_a3` names them all.
    bgv,
    offer,
    offer_approval,
    offer_closure,
    docreq,
    cover,
    cover_approval,
    requisition_a3,
    vendor_ext,
    analytics,
    hr_applicant_ext,
    pb_hiring,
    pb_hiring_a3,
    hiring_automation,
)
