import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const ctx=vm.createContext({structuredClone,assert});for(const name of ['data','engine','option2-core','option2-journey-core'])vm.runInContext(fs.readFileSync('src/'+name+'.js','utf8'),ctx);let count=0;
function test(name,code){try{vm.runInContext(code,ctx);count++;console.log('PASS '+name)}catch(e){process.exitCode=1;console.error('FAIL '+name,e)}}
test('Revised journey and old-draft migration preserve manual formulas',`{const b=newBlueprint();b.step=2;b.overrides.BASIC_SALARY='=1';initJourney(b);assert.equal(b.step,1);assert.equal(b.journey.revision,3);assert.equal(b.overrides.BASIC_SALARY,'=1');assert.equal(BLUEPRINT_STEPS[3],'Outputs & formulas');b.step=3;initJourney(b);assert.equal(b.step,3);}`);
test('All ten approval transactions retain source and controls',`{const b=initJourney(newBlueprint());assert.equal(b.journey.approvals.rows.length,10);assert.equal(b.journey.approvals.rows[8].object,'Bank payment release');assert.ok(b.journey.approvals.rows.every(r=>r.source&&r.evidence));assert.equal(validateApprovals(b.journey.approvals),true);}`);
test('Approval drafts are independent across schemas and survive skip',`{const a=initJourney(newBlueprint()),b=initJourney(newBlueprint());a.journey.approvals.rows[0].approver='Country Director';a.journey.approvals.status='skipped';assert.equal(optionalStatus(a,'approvals'),'skipped');assert.equal(a.journey.approvals.rows[0].approver,'Country Director');assert.equal(b.journey.approvals.rows[0].approver,'HR Lead');}`);
test('Approval validation rejects missing roles and maker self-review',`{const a=initJourney(newBlueprint()).journey.approvals;a.rows[0].reviewer=a.rows[0].maker;assert.throws(()=>validateApprovals(a),/Maker must differ/);a.rows[0].reviewer='Checker';a.rows[0].evidence='';assert.throws(()=>validateApprovals(a),/evidence/);}`);
test('All three synthetic sources map correctly to schema inputs',`{const b=initJourney(newBlueprint());for(const source of ['api','excel','models']){b.journey.mapping.source=source;b.journey.mapping.rows=seedMappings(source);const v=validateMappings(b);assert.equal(v.CONTRACT_SALARY,30000000);assert.equal(v.PAID_DAYS,22);assert.equal(Object.keys(v).length,6);}}`);
test('Mapping rejects duplicates, unknown targets and text into numeric input',`{const b=initJourney(newBlueprint());b.journey.mapping.rows.push({...b.journey.mapping.rows[0]});assert.throws(()=>validateMappings(b),/once/);b.journey.mapping.rows.pop();b.journey.mapping.rows[0].target='UNKNOWN';assert.throws(()=>validateMappings(b),/missing/);b.journey.mapping.rows[0].target='CONTRACT_SALARY';b.journey.mapping.rows[0].field='employee_id';assert.throws(()=>validateMappings(b),/numeric/);}`);
test('Mapped sample values are used by the actual Excel evaluator',`{const b=initJourney(newBlueprint()),s=sampleProfile();s.mappedInputs={CONTRACT_SALARY:40000000};assert.equal(runBlueprint(compileBlueprint(b),s).BASIC_SALARY,40000000);}`);
test('Payslip visibility, labels and sections do not alter payroll',`{const b=initJourney(newBlueprint()),before=runBlueprint(compileBlueprint(b),sampleProfile()).NET_PAY;b.journey.payslip.rows=seedPayslip(b);b.journey.payslip.rows[0].label='My base salary';b.journey.payslip.rows[0].section='summary';validatePayslip(b);assert.equal(runBlueprint(compileBlueprint(b),sampleProfile()).NET_PAY,before);}`);
test('Payslip requires net pay and catches removed component links',`{const b=initJourney(newBlueprint());b.journey.payslip.rows=seedPayslip(b);b.journey.payslip.rows.find(r=>r.code==='NET_PAY').show=false;assert.throws(()=>validatePayslip(b),/net pay/);b.journey.payslip.rows.find(r=>r.code==='NET_PAY').show=true;b.components.find(c=>c.code==='UNIFORM').included=false;assert.throws(()=>validatePayslip(b),/removed/);b.journey.payslip.status='configured';assert.equal(optionalStatus(b,'payslip'),'needs_review');}`);
test('Blank and Vietnam starting points actually replace components',`{const b=initJourney(newBlueprint());b.overrides.BASIC_SALARY='=1';applyStartingPoint(b,'blank');assert.equal(b.components.length,0);assert.equal(Object.keys(b.overrides).length,0);assert.equal(runBlueprint(compileBlueprint(b),sampleProfile()).NET_PAY,0);applyStartingPoint(b,'vietnam');assert.equal(b.components.length,38);}`);
test('Example Excel import creates valid editable rules',`{const b=initJourney(newBlueprint());applyStartingPoint(b,'excel');applySampleImport(b,stageSampleImport());assert.equal(b.components.length,4);assert.equal(b.journey.import.status,'sample_applied');assert.equal(runBlueprint(compileBlueprint(b),sampleProfile()).PROJECT_ALLOWANCE,750000);assert.ok(b.overrides.BASIC_SALARY.startsWith('='));}`);
test('Failed import preserves existing components atomically',`{const b=initJourney(newBlueprint()),rows=stageSampleImport();rows[0].formula='=MISSING_INPUT';assert.throws(()=>applySampleImport(b,rows),/missing/);assert.equal(b.components.length,38);assert.equal(Object.keys(b.overrides).length,0);}`);
test('Journey draft survives JSON round trip',`{const b=initJourney(newBlueprint());b.journey.mapping.status='skipped';b.journey.approvals.rows[0].delegate='Backup HR';const c=JSON.parse(JSON.stringify(b));initJourney(c);assert.equal(c.journey.mapping.status,'skipped');assert.equal(c.journey.approvals.rows[0].delegate,'Backup HR');}`);
test('Mapped day limits are validated against mapped inputs',`{const b=initJourney(newBlueprint());b.journey.mapping.rows[1].field='monthly_salary';assert.throws(()=>validateMappings(b),/Mapped paid days/);}`);
if(!process.exitCode)console.log(count+' journey checks passed');
